dist: trusty

language: cpp

compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
      - wget
      - coreutils
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel_0.4.4-linux-x86_64.deb
  - sudo dpkg -i bazel_0.4.4-linux-x86_64.deb

script:
  - bazel run @cpplint_archive//:cpplint $(find $(pwd) | grep -E "[.](h|cpp)$")
  - bazel test //... --test_output=streamed
