dist: trusty

language: cpp

compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
      - wget
      - coreutils
      - pkg-config

before_install:
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt-get -qq update
  - sudo apt-get install -y bazel

script:
  - bazel run @cpplint_archive//:cpplint $(find $(pwd) | grep -E "[.](h|cpp)$")
  - bazel test //... --test_output=streamed
