addons:
  apt:
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel_0.4.4-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.4.4-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.4.4-linux-x86_64.deb

script:
  - bazel test :all
