cc_library(
  name = "libtypegenerator",
  srcs = [
    "typegenerator.cpp",
  ],
  hdrs = [
    "typegenerator.h",
  ],
  deps = [
    "//lib/xsd:libxsd",
  ],
  copts = [
    "-I/usr/include/libxml2",
  ],
  visibility = ["//visibility:public"],
)
